### PR TITLE
done

### PR DESCRIPTION
**Pull request by multeng**
1. Task - [description](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task4-integration-with-database/task.md)
2. Crosscheck - [information](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task4-integration-with-database/task.md)
3. Deploy - [CloudFront link](http://dyhwz91va2tyf.cloudfront.net/), [Products](https://fki8nbpyz3.execute-api.eu-west-1.amazonaws.com/dev/products), [ProductsById](https://fki8nbpyz3.execute-api.eu-west-1.amazonaws.com/dev/product/90c51e85-0e62-4946-8675-27e879a29700), [addProduct](https://fki8nbpyz3.execute-api.eu-west-1.amazonaws.com/dev/products), [sqlscript](https://github.com/multeng/thrift-shop-be/blob/task4/service/sqlscript.sql)
4. Done - 8.09.21, Deadline:8.09.2021 23:59 GMT+3
5. 9 / 9 points.

### CODE REVIEW

**Comment by Vladqqqqoo** [comment]
you can find me in discord or just answer to this comment

**Comment by multeng** [comment]
> No problems, you can find me in discord or just answer to this comment

i think i done)

**Comment by Vladqqqqoo** [comment]
I'm sorry but I can't use post method.
I try to prodive next body:
``{
    "title": "abc",
    "description": "desc",
    "img": null,
    "price": 5000,
    "count": 2
}``

**Comment by Vladqqqqoo** [comment]
Also I don't see where you return 400 error for product creation proccess in case of bad request body
https://github.com/multeng/thrift-shop-be/blob/task4/service/src/functions/addProduct/handler.ts

**Pull request merged**
